eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48670.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48684.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48750.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48730.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48591.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48760.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48701.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48667.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48739.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48712.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48747.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48642.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48713.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48594.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48699.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48727.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48647.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48745.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48614.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48640.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48829.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48592.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48793.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48608.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48593.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48618.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48716.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48724.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48644.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48685.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48708.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48672.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48715.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48649.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48738.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48828.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48636.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48790.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48763.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48711.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48631.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48658.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48676.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48714.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48792.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48807.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48742.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48705.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48704.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48762.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48694.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48834.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48802.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48736.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48691.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48818.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48811.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48800.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48693.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48822.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48616.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m49468.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48785.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48638.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48661.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48692.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48700.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48776.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48761.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48683.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48759.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48662.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48689.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48766.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48813.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48659.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48827.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48668.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48680.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48795.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48695.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48637.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48825.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48590.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48696.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48748.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48671.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48660.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48773.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48630.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48639.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48814.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48768.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48628.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48767.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48809.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48626.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48732.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48643.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48729.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48663.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48629.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48632.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48720.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48737.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48709.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48749.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48754.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48687.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48674.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48646.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48678.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48733.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48625.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48741.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48651.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48621.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48619.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48824.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48648.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48718.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48725.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48669.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48820.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48641.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48770.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48710.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48722.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48726.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48723.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48652.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48611.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48703.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48753.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48645.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m50323.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48774.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48697.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48686.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48673.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48784.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48650.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48740.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48756.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48721.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48791.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48797.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48681.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48702.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48731.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48798.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48605.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48816.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48620.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48607.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48808.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48833.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48719.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48698.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48794.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48830.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48666.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48831.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48823.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48751.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48602.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48758.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48772.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48815.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48675.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48771.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48799.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48819.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48788.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48812.txt' &
wait
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48835.txt' &
eval 'java -cp stanford-corenlp-3.5.1.jar:stanford-corenlp-3.5.1-models.jar:xom.jar:joda-time.jar:slf4j-api.jar:jollyday.jar -Xmx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file /home/ashihara/PycharmProjects/study/data/Rice_University/economics_kari/m48734.txt' &
